import React, { createContext, useContext, useState } from 'react';

const translations = {
  en: {
    appName: 'NagarBot',
    reportIssue: 'Report Issue',
    myIssues: 'My Issues',
    myCases: 'My Cases',
    cityMap: 'City Map',
    dashboard: 'Dashboard',
    leaderboard: 'Leaderboard',
    logout: 'Logout',
    login: 'Login',
    register: 'Register',
    submitIssue: 'Submit Issue',
    submitting: 'Submitting & Analyzing...',
    issueTitle: 'Issue Title',
    description: 'Describe the issue in detail...',
    address: 'Address / Landmark',
    issueReported: '✅ Issue Reported!',
    category: 'Category',
    urgency: 'Urgency',
    department: 'Department',
    viewLetter: '📄 View Complaint Letter',
    downloadLetter: '⬇ Download Letter',
    viewOnMap: 'View on Map',
    status: 'Status',
    upvotes: 'upvotes',
    upvote: 'Upvote',
    reported: 'Reported',
    inProgress: 'In Progress',
    resolved: 'Resolved',
    karma: 'Karma',
    topReporters: 'Top Reporters',
    issues: 'Issues',
    chatPlaceholder: 'Ask me about civic issues...',
    send: 'Send',
    chatTitle: 'NagarBot Assistant',
    timeline: 'Issue Timeline',
    noIssues: 'No issues reported yet.',
    locationDetected: '📍 Location detected',
  },
  hi: {
    appName: 'नगरबॉट',
    reportIssue: 'समस्या दर्ज करें',
    myIssues: 'मेरी समस्याएं',
    myCases: 'मेरे मामले',
    cityMap: 'शहर का नक्शा',
    dashboard: 'डैशबोर्ड',
    leaderboard: 'लीडरबोर्ड',
    logout: 'लॉग आउट',
    login: 'लॉग इन',
    register: 'पंजीकरण',
    submitIssue: 'समस्या जमा करें',
    submitting: 'जमा हो रहा है...',
    issueTitle: 'समस्या का शीर्षक',
    description: 'समस्या का विवरण दें...',
    address: 'पता / स्थान',
    issueReported: '✅ समस्या दर्ज हो गई!',
    category: 'श्रेणी',
    urgency: 'तात्कालिकता',
    department: 'विभाग',
    viewLetter: '📄 शिकायत पत्र देखें',
    downloadLetter: '⬇ पत्र डाउनलोड करें',
    viewOnMap: 'नक्शे पर देखें',
    status: 'स्थिति',
    upvotes: 'वोट',
    upvote: 'वोट करें',
    reported: 'दर्ज',
    inProgress: 'प्रगति में',
    resolved: 'हल हो गया',
    karma: 'कर्मा',
    topReporters: 'शीर्ष रिपोर्टर',
    issues: 'समस्याएं',
    chatPlaceholder: 'नागरिक समस्याओं के बारे में पूछें...',
    send: 'भेजें',
    chatTitle: 'नगरबॉट सहायक',
    timeline: 'समस्या टाइमलाइन',
    noIssues: 'अभी तक कोई समस्या दर्ज नहीं।',
    locationDetected: '📍 स्थान मिला',
  },
  pa: {
    appName: 'ਨਗਰਬੋਟ',
    reportIssue: 'ਸਮੱਸਿਆ ਦਰਜ ਕਰੋ',
    myIssues: 'ਮੇਰੀਆਂ ਸਮੱਸਿਆਵਾਂ',
    myCases: 'ਮੇਰੇ ਕੇਸ',
    cityMap: 'ਸ਼ਹਿਰ ਦਾ ਨਕਸ਼ਾ',
    dashboard: 'ਡੈਸ਼ਬੋਰਡ',
    leaderboard: 'ਲੀਡਰਬੋਰਡ',
    logout: 'ਲੌਗ ਆਊਟ',
    login: 'ਲੌਗ ਇਨ',
    register: 'ਰਜਿਸਟਰ',
    submitIssue: 'ਸਮੱਸਿਆ ਜਮ੍ਹਾਂ ਕਰੋ',
    submitting: 'ਜਮ੍ਹਾਂ ਹੋ ਰਿਹਾ ਹੈ...',
    issueTitle: 'ਸਮੱਸਿਆ ਦਾ ਸਿਰਲੇਖ',
    description: 'ਸਮੱਸਿਆ ਦਾ ਵੇਰਵਾ ਦਿਓ...',
    address: 'ਪਤਾ / ਸਥਾਨ',
    issueReported: '✅ ਸਮੱਸਿਆ ਦਰਜ ਹੋ ਗਈ!',
    category: 'ਸ਼੍ਰੇਣੀ',
    urgency: 'ਜ਼ਰੂਰੀਅਤ',
    department: 'ਵਿਭਾਗ',
    viewLetter: '📄 ਸ਼ਿਕਾਇਤ ਪੱਤਰ ਦੇਖੋ',
    downloadLetter: '⬇ ਪੱਤਰ ਡਾਊਨਲੋਡ ਕਰੋ',
    viewOnMap: 'ਨਕਸ਼ੇ ਤੇ ਦੇਖੋ',
    status: 'ਸਥਿਤੀ',
    upvotes: 'ਵੋਟਾਂ',
    upvote: 'ਵੋਟ ਕਰੋ',
    reported: 'ਦਰਜ',
    inProgress: 'ਚੱਲ ਰਿਹਾ ਹੈ',
    resolved: 'ਹੱਲ ਹੋ ਗਿਆ',
    karma: 'ਕਰਮਾ',
    topReporters: 'ਚੋਟੀ ਦੇ ਰਿਪੋਰਟਰ',
    issues: 'ਸਮੱਸਿਆਵਾਂ',
    chatPlaceholder: 'ਨਾਗਰਿਕ ਸਮੱਸਿਆਵਾਂ ਬਾਰੇ ਪੁੱਛੋ...',
    send: 'ਭੇਜੋ',
    chatTitle: 'ਨਗਰਬੋਟ ਸਹਾਇਕ',
    timeline: 'ਸਮੱਸਿਆ ਟਾਈਮਲਾਈਨ',
    noIssues: 'ਹੁਣ ਤੱਕ ਕੋਈ ਸਮੱਸਿਆ ਦਰਜ ਨਹੀਂ।',
    locationDetected: '📍 ਸਥਾਨ ਮਿਲਿਆ',
  },
};

const LangContext = createContext();

export const LangProvider = ({ children }) => {
  const [lang, setLang] = useState(localStorage.getItem('lang') || 'en');
  const t = (key) => translations[lang][key] || translations.en[key] || key;
  const switchLang = (l) => { setLang(l); localStorage.setItem('lang', l); };
  return <LangContext.Provider value={{ lang, t, switchLang }}>{children}</LangContext.Provider>;
};

export const useLang = () => useContext(LangContext);
